packages:
  - "backend/*"
  - "frontend/*"

onlyBuiltDependencies:
  - esbuild

ignoredBuiltDependencies:
  - "@scarf/scarf"
allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: false
  core-js-pure: false
  esbuild: true

overrides:
  multer: ^2.2.0
  js-yaml: ^4.1.2
